### ISSUE TITLE
[Feature Request] Searching overwin like easymotion-overwin

### ISSUE THREAD

**Issue by hungpham3112** [monkoose/vim9-stargate#13]
I find the easymotion-overwin really handy and intuitive to jump to character. Is there any similar functionality in this plugin? If not, do you have any plan for stargate-overwin?  Thank you.

**Comment by monkoose** [comment]
Not perfect, but you can hit `<C-w>` when plugin is activated and then switch to a label.

As of adding something new to this plugin - don't really have any desire to improve it (at least in the near future).
