### ISSUE TITLE
After switching tabs, the regular matching jump can no longer pop up.

### ISSUE THREAD

**Issue by qindapao** [monkoose/vim9-stargate#14]
@monkoose Thanks to this plug-in, I can jump without temporarily modifying the buffer.

But I found a little problem

Here are my keybindings

```vim
nnoremap <c-;> <Cmd>call stargate#OKvim('\<')<cr>
```

![image](https://github.com/monkoose/vim9-stargate/assets/109883544/6595186e-8394-4fae-8562-f173b5db4be5)

But if you switch tabs, the jump mark of the pop-up window will not pop up.

![image](https://github.com/monkoose/vim9-stargate/assets/109883544/58a70fe6-d97e-4a92-864f-a405ea883b8c)

I made a rough analysis and found that the pop-up window used after switching tabs was occupied by the previous tab and was not cleaned up.

Below is a temporary fix I made myself in my vimrc.

```vim
function! ClearAllNotTipsPopupWin()
    let all_popup_win_list = popup_list()
    if all_popup_win_list != []
        for winid in all_popup_win_list
            if get(popup_getoptions(winid), "title", "") != "tips"
                call popup_close(winid)
            endif
        endfor
    endif

endfunction
autocmd TabLeave * call ClearAllNotTipsPopupWin()
```

The "tips" above are pop-up windows that I defined myself. I filtered them so as not to close them too.

**Comment by monkoose** [comment]
Thank you for reporting. Currently I'm away from my PC for a few days, when I'll get back, I will look what can be done.

**Comment by monkoose** [comment]
Should be fixed now.

**Comment by qindapao** [comment]
@monkoose Thank you, it was fixed. I have deleted my temporary fix.
