### ISSUE TITLE
When enable virtual text, highlight position is incorrect

### ISSUE THREAD

**Issue by yu3s** [monkoose/vim9-stargate#15]
Thanks for your plugin, I found that highlight position is incorrect when enable virtual text(https://github.com/yegappan/lsp)

1. 
![step1](https://github.com/monkoose/vim9-stargate/assets/86161857/45afa410-25e4-48a5-9a07-e5bc8c36df40)
2. 
![step2](https://github.com/monkoose/vim9-stargate/assets/86161857/3458e3e3-e46d-4c67-afcd-a66d61ced306)

---
btw: my modified version based on yours is as follows，for personal use only
```vim
vim9script noclear

highlight default JumpFocus			guifg=#958c6a
highlight default JumpMain			guifg=#f2119c gui=bold cterm=bold

const limit = 200
var table: list<dict<any>>

def Init()
	var name: string
	var str: list<string> = 'fjdklshgaewiomc'->split('\zs')
	var len: number = str->len()

	for idx in range(limit)
		table->add({'name': str[idx / len] .. str[idx % len]})

		name = table[idx]['name']
		table[idx][name] = popup_create(name, {hidden: true, wrap: false, tabpage: -1, highlight: "JumpMain"})
	endfor
enddef

def Show(lnum: number, end: number)
	var len: number
	var ch: string
	var id: number
	var status: number
	var screen_pos: dict<any>
	var input: string

	id = matchaddpos("JumpFocus", range(lnum, end))
	defer matchdelete(id)
	redraw

	ch = nr2char(getchar())

	for row in range(lnum, end)
		var current = getline(row)
		for str in matchstrlist([current], '\<\k\+\>')
			if str.text =~? ch
				table[len]['pos'] = {'lnum': row, 'end': str['byteidx'] + 1, 'virt': 0}

				for item in prop_list(row)
					if item['col'] == str['byteidx'] + 1
						table[len]['pos']['virt'] = len(item['text'])
					endif
				endfor

				len += 1
			endif
		endfor
	endfor

	if len == 0
		return
	elseif len >= limit
		len = limit
	endif

	for idx in range(len)
		screen_pos = screenpos(winnr(), table[idx]['pos']['lnum'], table[idx]['pos']['end'])

		popup_move(table[idx][table[idx].name], {line: screen_pos.row, col: screen_pos.col + table[idx]['pos']['virt']})
		popup_show(table[idx][table[idx].name])
	endfor
	redraw

	for _ in range(2)
		input ..= nr2char(getchar())

		if input !~# '\l'
			break
		endif
	endfor

	for idx in range(len)
		if table[idx]->has_key(input)
			cursor(table[idx]['pos']['lnum'], table[idx]['pos']['end'])
		endif

		popup_hide(table[idx][table[idx].name])
	endfor
enddef

export def Jump()
	var conceal: number

	if table->empty()
		Init()
	endif

	conceal = &conceallevel
	&conceallevel = 0
	Show(line('w0'), line('w$'))
	&conceallevel = conceal
enddef
```

**Comment by monkoose** [comment]
Thanks for reporting. The plugin was made before inlay hints with virtual text were added to vim.
Fixing this is not my priority for now, because I'm not using such a feature myself (and not planning), but I will look at free time if there is an easy api to get positions and length of the virtual text chunks on specific line, otherwise it could take more time to fix this. PR or advises (if you familiar with vim virtual text api) are welcome.

**Comment by monkoose** [comment]
I did small tests. Are you sure you are using my plugin to test this and not your custom implementation?

For a buffer that contains `hello world` text
If i add virtual text with 
```vim
call prop_type_add('inlay', {'highlight': 'Error'})
call prop_add(line('.'), 6, {'type': 'inlay', 'text': 'inlay'})
call prop_add(line('.'), 10, {'type': 'inlay', 'text': 'inlay'})
```
I still can jump to labels and the labels are correctly shown.

**Comment by yu3s** [comment]
> I did small tests. Are you sure you are using my plugin to test this and not your custom implementation?
> 
> For a buffer that contains `hello world` text If i add virtual text with
> 
> ```viml
> call prop_type_add('inlay', {'highlight': 'Error'})
> call prop_add(line('.'), 6, {'type': 'inlay', 'text': 'inlay'})
> call prop_add(line('.'), 10, {'type': 'inlay', 'text': 'inlay'})
> ```
> 
> I still can jump to labels and the labels are correctly shown.

1. cat 1.vim
```vim
vim9script

prop_type_add('inlay', {'highlight': 'Error'})

prop_add(5, 8, {'type_bufnr': 0, 'type': 'inlay', 'text': 'stream: '})
```
2. `vim 1.vim -c "so %"`
3. call stargate#OKvim(1) for search `d`
4. 
![Screenshot from 2024-01-17 20-00-28](https://github.com/monkoose/vim9-stargate/assets/86161857/7994ce60-578e-4211-b52a-c2e10f9e5230)

**Comment by yu3s** [comment]
I use the lsp plugin(https://github.com/yegappan/lsp) to test, just enter the command `LspInlayHints enable`
The example I provided may not be appropriate, and  only part of it shows incorrect
![Screenshot from 2024-01-17 20-13-20](https://github.com/monkoose/vim9-stargate/assets/86161857/4124847a-a033-4268-84f6-86098a21420f)

![Screenshot from 2024-01-17 20-11-41](https://github.com/monkoose/vim9-stargate/assets/86161857/641d182e-db41-4462-89a2-5a4d5391628a)
such as L55 and L68

**Comment by monkoose** [comment]
68 is fine. 55 is wrong. It happens when a popup label should be placed at the column the same where virtual text was placed, the actual character is shifted to the length of the virtual text, but popup is still placed at the start of the virtual text. For me it sounds like a vim issue. Don't think there can be much done from the plugin. My assumption that if the plugin will detect that at the same position there is virtual text then shifting label to +1 column will still place label in the wrong position (shifted 1 character after the required).

**Tested**: Ok, my assumption was wrong. It could be fixed, but will required some work, not sure when I will have time to do it.

**Comment by yu3s** [comment]
> 68 is fine. 55 is wrong. It happens when a popup label should be placed at the column the same where virtual text was placed, the actual character is shifted to the length of the virtual text, but popup is still placed at the start of the virtual text. For me it sounds like a vim issue. Don't think there can be much done from the plugin. My assumption that if the plugin will detect that at the same position there is virtual text then shifting label to +1 column will still place label in the wrong position (shifted 1 character after the required).

thanks, I'm not sure, but I don't need to jump to a certain character, just the word containing that character.
The functions I implemented have met my personal needs

**Comment by monkoose** [comment]
Seems like fix was easier than I expected. Can you test it with the last commit, please?

**Comment by yu3s** [comment]
> Seems like fix was easier than I expected. Can you test it with the last commit, please?

it works, thanks

**Comment by yu3s** [comment]
btw: final configuration, need Vim 9.1.0027+
```vim
vim9script noclear

highlight default JumpFocus			guifg=#958c6a
highlight default JumpMain			guifg=#f2119c gui=bold cterm=bold

const limit = 200
var table: list<dict<any>>

def Init()
	var name: string
	var str: list<string> = 'fjdklshgaewiomc'->split('\zs')
	var len: number = str->len()

	for idx in range(limit)
		table->add({'name': str[idx / len] .. str[idx % len]})

		name = table[idx]['name']
		table[idx][name] = popup_create(name, {hidden: true, wrap: false, tabpage: -1, highlight: "JumpMain"})
	endfor
enddef

def Show(lnum: number, end: number)
	var len: number
	var ch: string
	var id: number
	var screen_pos: dict<any>
	var input: string

	id = matchaddpos("JumpFocus", range(lnum, end))
	defer matchdelete(id)
	redraw

	ch = nr2char(getchar())
	len = foreach(matchbufline(bufnr(), '\<\k\+\>', lnum, end)
		->filter((_, v) => v.text =~? ch),
		"table[v:key]['pos'] = v:val")->len()

	if len == 0
		return
	elseif len >= limit
		len = limit
	endif

	for idx in range(len)
		screen_pos = screenpos(winnr(), table[idx]['pos']['lnum'], table[idx]['pos']['byteidx'] + 1)

		popup_move(table[idx][table[idx].name], {line: screen_pos.row, col: screen_pos.curscol})
		popup_show(table[idx][table[idx].name])
	endfor
	redraw

	for _ in range(2)
		input ..= nr2char(getchar())

		if input !~# '\l'
			break
		endif
	endfor

	for idx in range(len)
		if table[idx]->has_key(input)
			cursor(table[idx]['pos']['lnum'], table[idx]['pos']['byteidx'] + 1)
		endif

		popup_hide(table[idx][table[idx].name])
	endfor
enddef

export def Jump()
	var conceal: number

	if table->empty()
		Init()
	endif

	conceal = &conceallevel
	&conceallevel = 0
	Show(line('w0'), line('w$'))
	&conceallevel = conceal
enddef
```
