### ISSUE TITLE
Possible name conflict when importing

### ISSUE THREAD

**Issue by obcat** [monkoose/vim9-stargate#3]
## Problem

A name conflict might happen when:

- A. This plugin user do `:import` somewhere else.

- B. We do `:import` in this plugin.

### Case A

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script

    set runtimepath=/tmp/.vim/plugged/vim9-stargate,/tmp/.vim/plugged/vim9-library
    delete('/tmp/.vim', 'rf')
    system('git clone https://github.com/monkoose/vim9-stargate.git /tmp/.vim/plugged/vim9-stargate')
    mkdir('/tmp/.vim/plugged/vim9-library/import', 'p')
    var lines =<< trim END
      " messages.vim
      vim9script
      export def StandardMessage()
        echomsg 'This is a standart message'
      enddef
    END
    writefile(lines, '/tmp/.vim/plugged/vim9-library/import/messages.vim')

    import StandardMessage from 'messages.vim'
    StandardMessage()
    ```

    This error is raised from the last line:

    ```
    E119: Not enough arguments for function: StandardMessage
    ```

    While one would expect "This is a standart messages" to be echo'ed.

### Case B

1. Run `vim --clean`.

1. Source this script:

    ```vim
    vim9script

    set runtimepath=/tmp/.vim/plugged/vim9-library,/tmp/.vim/plugged/vim9-stargate
    delete('/tmp/.vim', 'rf')
    system('git clone https://github.com/monkoose/vim9-stargate.git /tmp/.vim/plugged/vim9-stargate')
    mkdir('/tmp/.vim/plugged/vim9-library/import', 'p')
    var lines =<< trim END
      " messages.vim
      vim9script
      export def StandardMessage()
        echomsg 'This is a standart message'
      enddef
    END
    writefile(lines, '/tmp/.vim/plugged/vim9-library/import/messages.vim')

    noremap \f <Cmd>call stargate#ok_vim(1)<CR>
    ```

1. Type `\f`.

    A sequence of errors is raised, like this:

    ```
    Error detected while processing /tmp/.vim/plugged/vim9-stargate/autoload/stargate.vim[4]../tmp/.vim/plugged/vim9-stargate/import/vim9000.vim[4]../tmp/.vim/plugged/vim9-stargate/import/galaxies.vim:
    line    3:
    E1048: Item not found in script: StandardMessage
    Error detected while processing /tmp/.vim/plugged/vim9-stargate/autoload/stargate.vim[4]../tmp/.vim/plugged/vim9-stargate/import/vim9000.vim:
    line    4:
    E1048: Item not found in script: ChangeGalaxy
    ...
    ```

    While one would expect stargate to be started.

## Suggestion

First, to avoid the conflict in the case A, we can rename "import/" to "\_import/", "private/", etc.:

```
import/galaxies.vim -> _import/galaxies.vim
import/messages.vim -> _import/messages.vim
import/stargates.vim -> _import/stargates.vim
import/vim9000.vim -> _import/vim9000.vim
import/workstation.vim -> _import/workstation.vim
```

And then use [the relative path form](https://github.com/vim/vim/blob/c816a2c22667108fcd61f445de2c926f78ff9fa7/runtime/doc/vim9.txt#L1358) for the script name when `:import`ing in our scripts:

```vim
import { CreatePopups } from '../_import/workstation.vim'
import { OkVIM } from '../_import/vim9000.vim'
import { ChangeGalaxy } from '../_import/galaxies.vim'
```

Which avoids name conflict in the case B as a result.

If we want to supply "import/\*.vim" as library scripts, then we can gather them in "import/stargate/" directory instead:

```
import/galaxies.vim -> import/stargate/galaxies.vim
import/messages.vim -> import/stargate/messages.vim
import/stargates.vim -> import/stargate/stargates.vim
import/vim9000.vim -> import/stargate/vim9000.vim
import/workstation.vim -> import/stargate/workstation.vim
```

So that user can import by using this handy form for the script name:

```vim
import ErrorMessage from stargate/messages.vim
```

This way, name conflict which user wouldn't expect will not happen, since the script name is prefixed with the "stargate/" namespace.

And then we should use the relative path form in our scripts as well:

```vim
import { CreatePopups } from '../import/stargate/workstation.vim'
import { OkVIM } from '../import/stargate/vim9000.vim'
import { ChangeGalaxy } from '../import/stargate/galaxies.vim'
```

Although we can use this form with no worry about name conflicts:

```vim
import { CreatePopups } from 'stargate/workstation.vim'
import { OkVIM } from 'stargate/vim9000.vim'
import { ChangeGalaxy } from 'stargate/galaxies.vim'
```

Because [the relative path form is more efficient](https://github.com/vim/vim/blob/c816a2c22667108fcd61f445de2c926f78ff9fa7/runtime/doc/vim9.txt#L1682).

## Additional context

If you wish, I'll create PR. Please let me know :)

## Environment

 - Vim 8.2.3134
 - vim9-stargate https://github.com/monkoose/vim9-stargate/commit/e30bd1afa0bc8dc446f9836d46045eb11099cbfb
 - macOS Catalina (version 10.15.7)

**Comment by monkoose** [comment]
Hello, thank you for this investigation. I have done 0 research how vim9 import works, thought it is plugin local only.
Will definitely fix this.

**Comment by monkoose** [comment]
I think i will stick with 'private' version of `_import`, because of the naming conventions i'm not sure any of this plugin scripts has any value as some library. What do you think?

**Comment by obcat** [comment]
Hello, thank you for the reply and working on this issue.

> I think i will stick with 'private' version of `_import`, because of the naming conventions i'm not sure any of this plugin scripts has any value as some library. What do you think?

Unfortunately, I don't have enough experience  to judge if using "private" is a good choice in terms of naming convention, but I could find a plugin which uses "private":

https://github.com/Bakudankun/qline.vim

**Comment by monkoose** [comment]
Ok. Then i will just do `_import` to not clutch with user defined functions.
Thank you.

Also i have found that this qline plugin uses `import * as ...`, so it is already implemented? Need to update my vim then.

**Comment by obcat** [comment]
Thanks for the fix!
Please note that we can rename the directory whenever we want, since the scripts are now almost private.

> Also i have found that this qline plugin uses `import * as ...`, so it is already implemented?

Probably yes, let's try it out ;)
