### ISSUE TITLE
E1263 error occurs in recent Vim9 script

### ISSUE THREAD

**Issue by kg8m** [monkoose/vim9-stargate#8]
Hi. I love vim9-stargate. It helps me every day!

In recent Vim9 script, I get an error `E1263: cannot use name with # in Vim9 script, use export instead` when calling `stargate#ok_vim()` or `stargate#galaxy()`. The error occurs because current Vim9 script doesn't allow function names defined by `:def` to contain `#` or start with a lowercase character.

I think there are 2 options to resolve the issue.

1. Rename the functions, e.g., `stargate#OKVim()` and `stargate#Galaxy()`
   * Pros
     * A little codes need fixing
   * Cons
     * vim9-stargate users need to fix their `vimrc`
     * The documentations (`README.md` and `doc/stargate.txt`) to be fixed are a lot
3. Define `stargate#ok_vim()` and `stargate#galaxy()` in legacy Vim script
   * Pros
     * The public user interfaces aren't changed
       * vim9-stargate users don't need to fix their `vimrc`
       * The documentations don't need fixing
   * Cons
     * A lot of codes need fixing
       * Note: Most of them are only moved to a different file
     * Legacy Vim scripts are contained in the code base

I will create a pull request if you are positive about one of the options. Can you tell me your thoughts?

Best regards.

**Comment by monkoose** [comment]
Hello, can you point to commit in the vim repo with that change? How recent it is?

**Comment by kg8m** [comment]
Thank you for the reply!

The issue has been present since v8.2.4264 (https://github.com/vim/vim/commit/d8fe6d34bb582438142d7c1f73d0bd8537bb3a7a).

**Comment by monkoose** [comment]
Should be fixed in a30edd8f374a2627187af19bb246efd5182cc58c
+ added info message on errors, so users can find what is going on and how to fix the issue.

**Comment by monkoose** [comment]
And thank You again for notifying me about some problems with vim9 updates, because currently I'm using neovim, so can miss such issues.

**Comment by kg8m** [comment]
Thanks for the reply, the fix, and for letting me know you are using Neovim.

I confirm that the issue has been fixed by a30edd8f374a2627187af19bb246efd5182cc58c.

Note: we also need to fix the `end` to `endif` in line 198 of `_import/vim9000.vim` because recent Vim doesn't allow `:end` in Vim9 script. Shall I create a pull request?

**Comment by monkoose** [comment]
> we also need to fix the end to endif in line 198 of _import/vim9000.vim because recent Vim doesn't allow :end in Vim9 script. Shall I create a pull request?

I think it was just mistype. Not sure if it ever were allowed.
Yes, You can do it. I don't mind.
